I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script call
    call scene_12 from _call_scene_12
  File "game/script.rpy", line 980, in script
    if sum(answers >= 7):
  File "game/script.rpy", line 980, in <module>
    if sum(answers >= 7):
TypeError: '>=' not supported between instances of 'RevertableList' and 'int'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script call
    call scene_12 from _call_scene_12
  File "game/script.rpy", line 980, in script
    if sum(answers >= 7):
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 980, in <module>
    if sum(answers >= 7):
TypeError: '>=' not supported between instances of 'RevertableList' and 'int'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
The CodeQueen 1.0
Mon Dec 25 15:11:29 2023
