I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script call
    call scene_10 from _call_scene_10
  File "game/script.rpy", line 823, in script call
    call go_back from _call_go_back
  File "game/script.rpy", line 861, in script call
    call site
  File "game/script.rpy", line 890, in script
    if not renpy.check_key(1):
  File "game/script.rpy", line 890, in <module>
    if not renpy.check_key(1):
AttributeError: module 'renpy.exports' has no attribute 'check_key'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script call
    call scene_10 from _call_scene_10
  File "game/script.rpy", line 823, in script call
    call go_back from _call_go_back
  File "game/script.rpy", line 861, in script call
    call site
  File "game/script.rpy", line 890, in script
    if not renpy.check_key(1):
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 890, in <module>
    if not renpy.check_key(1):
AttributeError: module 'renpy.exports' has no attribute 'check_key'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
The CodeQueen 1.0
Thu Dec 28 02:38:20 2023
